* DONE API
  CLOSED: [2015-05-11 一 22:58]
  - State "DONE"       from "HOLD"       [2015-05-11 一 22:58]
  - State "HOLD"       from ""           [2015-05-07 四 20:38]

  大概就是基于 canvas2svg 提供一组原始的 API 支持类似 `circle()` 之类的用法。
注意：不提供 c = circle() 是因为在 p5.js 中这默认是返回 this 来允许链式调用的。
同时提供 `new Circle()` 这样的语法

* DONE figure out how p5.dom.js comes out
  CLOSED: [2015-05-07 四 20:43]
  https://github.com/processing/p5.js/commits/6666c757e498b639f99126ebace5ee371aa09247/lib/addons/p5.dom.js

  似乎不是生成的，而是直接写在 lib/addons 里的，可以在 github commit log 里看出一些踪迹来

* DONE How createElement works?
  CLOSED: [2015-05-07 四 20:35]

  p5.prototype.createElement is defined in p5.js/lib/addons/p5.dom.js

* CANCELLED createCircle, createRect...
  CLOSED: [2015-05-07 四 20:53]
  - State "CANCELLED"  from ""           [2015-05-07 四 20:53]

    可能不是很有必要，因为已经有 Mover API 了，而这样又会污染一大堆 API

* TODO SVGFilter or MoverFilter

* DONE 提供基于 canvas2svg 的 API
  CLOSED: [2015-05-11 一 22:58]

  这样可以保证能够得到一致的 API，一份代码简单改改就能同时跑在 canvas 和 svg 中。
  而且对于不同的 shape，只要按照 canvas api 做一份就好，svg 直接也拿到支持。这样是非常棒的。

* DONE AMD, CMD & CommonJS
  CLOSED: [2015-05-09 六 23:52]

  http://www.cnblogs.com/skylar/p/4065455.html

  AMD: https://github.com/amdjs/amdjs-api/wiki/AMD-%28%E4%B8%AD%E6%96%87%E7%89%88%29

  CMD: https://github.com/seajs/seajs/issues/242

* DOING GC

** 保证始终有一代存在就好了

** 每次尝试 gc 的时候就创建新一代，然后 do gc 到仅剩一代

* canvas2svg

** pull request: reuse __createElement
